#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 29 01:21:51 2020

@author: teesha
"""

import numpy as np
import matplotlib.pyplot as plt

# Friction factor in a pipe
rr= 4.6e-3 #relative roughness in cm
density= 998 # Kg/m^3
d_vis= 0.001005 # N*s/m^2
d= 1.7120

#Define the function for laminar flow
def fF_L(Re):
    return 64./Re_L

#Define the function for turbulant flow
    #using Swamee-Jain
def fF_T(Re):
    left_side=(rr/d)/3.7
    right_side= 5.74/(Re_T**0.9)
    den= np.log10(left_side + right_side)**2
    result= 0.25/den
    return result
   

Re_L=np.linspace(800, 2.3e3, 1e3)
f1=fF_L(Re_L)

# Turbulant:
Re_T=np.linspace(2.3e3,100e3, 3e3)
f2=fF_T(Re_T)

plt.figure(figsize=(15,7))
plt.plot(Re_L, f1,'-b', label='Laminar')
plt.plot(Re_T, f2, '-r', label='Turbulant')
plt.xticks(np.arange(0, 10e5, 10e3))
plt.xscale('log')
plt.yticks(np.arange(0.02, 0.09, 0.015))
plt.xlabel('Reynolds number')
plt.ylabel('Friction factor')
plt.grid()
plt.legend()

#plt.show()
plt.savefig('pipe.png')